### ISSUE TITLE
RSS feed is missing

### ISSUE THREAD

**Issue by fsi** [CommitteeOfZero/committeeofzero.github.io#7]
Hello.

I noticed that this site has a `link` tag to an RSS feed like this:

```
<link rel="alternate" type="application/rss+xml" title="Committee of Zero" href="/feed.xml">
```

...but the feed itself is not generated (GET http://sonome.dareno.me/feed.xml returns 404 Not Found).
This is quite annoying when you try to follow your news with a feed reader.

Presumably, this can be fixed with a couple of lines, by adding

```
plugins:
  - jekyll-feed
```

to the config.yml

I can make a pull request with that

**Comment by rainx0r** [comment]
No excuse for why this took so long, we just failed to notice I suppose. The XML feed should be generated now.
